# Generated by Django 3.2.13 on 2022-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a suite name (e.g. 'A', 'B', 'C', etc.)", max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the suite', max_length=1000)),
                ('price', models.IntegerField(help_text='Enter the price of the suite')),
                ('photo', models.ImageField(blank=True, help_text='Upload a photo of the suite', upload_to='suites/photos')),
                ('available', models.BooleanField(default=True, help_text='Is the suite available?')),
            ],
        ),
    ]
